Add ability to use cursor pagination with beanie
uriyyo/fastapi-pagination pull request #1249
Opened 2024-08-16 10:26 UTC by shepilov-vladislav

2024-08-22 21:15 UTC, uriyyo reviewed
LGTM, I just have one question

2024-08-22 21:15 UTC, uriyyo commented on fastapi_pagination/ext/beanie.py
> +                            "$gt": PydanticObjectId(raw_params.cursor),  # type: ignore[attr-defined]
Can it raise an exception? Can we add validation that `cursor` is valid `PydanticObjectId`?

2024-08-26 17:54 UTC, shepilov-vladislav commented
@uriyyo I also added a backwards pass with testing, but I can't figure out why it works for `Document` and doesn't work for `Document.find()`

2024-09-08 12:15 UTC, uriyyo requested changes
Could you please take a look at why tests are failing?

2025-02-02 14:29 UTC, uriyyo commented
Hi @shepilov-vladislav,

Sorry for long response, are you sitll interested in this PR? Could you please resolve conflicts? I would like to merge this PR.

2025-02-07 13:37 UTC, shepilov-vladislav commented
@uriyyo Updated!

2025-02-07 16:47 UTC, uriyyo commented
Thanks 🙌

2025-02-07 16:48 UTC, uriyyo approved these changes
LGTM!

2025-02-07 16:51 UTC, merged