adds support for mongo paginate pipelines
uriyyo/fastapi-pagination pull request #233
Opened 2021-11-11 20:51 UTC by markbaas

Had some problems implementing the tests. Perhaps you could give me some instructions here.

2021-11-12 07:47 UTC, zsltg commented
> 
> 
> Had some problems implementing the tests. Perhaps you could give me some instructions here.

I haven't looked into this in detail (@uriyyo please correct me if I am wrong), but I believe with the current test setup, instead of including both in the same file, you would need to create a separate one and include the tests for the aggregate there, eg. `test_motor_aggregate.py`.

You can try to run it locally and see if it works:

`docker run -p 27017:27017 --name mongo -d mongo:5.0.3`
`poetry run pytest tests/ext/test_motor_aggregate.py --cov-report=xml --ignore=tests/ext/test_async_sqlalchemy.py --ignore=tests/ext/test_sqlalchemy_future.py --ignore=tests/ext/test_sqlmodel.py`

You can also run the whole test workflow with [act](https://github.com/nektos/act), the test cases pass, only the Codecov upload will fail.

2021-11-14 15:53 UTC, uriyyo commented
@zsltg Thanks, for the detailed explanation.

@markbaas Please, follow `Zsolt` instruction.

2021-11-22 08:37 UTC, uriyyo requested changes
LGTM in general.

Only a few minor things, please remove commented code and run pre-commit hooks, because the lint stage is failing.

To run pre-commit hooks locally you can run the following command:
```sh
poetry run pre-commit run --all-files
```

2021-11-22 08:37 UTC, uriyyo commented on tests/ext/test_motor_aggregate.py
> +        # db_client.drop_database("test")
Please, remove commented code.

2021-11-22 08:37 UTC, uriyyo commented on tests/ext/test_motor_aggregate.py
> +        # cursor = db_client.test.users.find()
Please, remove commented code.

2021-11-22 08:37 UTC, uriyyo commented on tests/ext/test_motor_aggregate.py
> +        # return [{"name": x["name"]} for x in items]
Please, remove commented code.

2022-01-03 07:46 UTC, uriyyo commented
@markbaas Do you have plans to update this PR?

2022-01-14 09:43 UTC, markbaas commented
> @markbaas Do you have plans to update this PR?

sorry done!

2022-01-14 10:15 UTC, uriyyo approved these changes
LGTM

2022-01-22 09:40 UTC, merged