Added django ORM support
uriyyo/fastapi-pagination pull request #59
Opened 2021-04-13 13:27 UTC by lingster

Add pagination if you are using django as the orm with fastapi.

2021-04-13 14:58 UTC, uriyyo commented
@lingster Could you please add tests to cover this feature?

2021-04-13 15:23 UTC, uriyyo requested changes

2021-04-13 15:23 UTC, uriyyo commented on fastapi_pagination/ext/django.py
> +# from django to pydantic
I am curious about, why we can't use pydantic `orm_mode =True` to parse models?

2021-04-19 21:59 UTC, lingster commented on fastapi_pagination/ext/django.py
> +# from django to pydantic
I was not aware of this feature! How does that work? 
Am presently struggling to get the the tests written. Will update once I have some time.

2021-04-20 06:32 UTC, uriyyo commented
Hi @lingster,

Could you please rebase on master? I will merge it and add tests by myself)

2021-04-20 10:40 UTC, merged

2021-04-20 10:41 UTC, uriyyo commented
@lingster Thanks)

2021-04-20 10:41 UTC, lingster commented
Hi @urlyyo,
That should be done.